---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crapi-tls
  namespace: crapi
spec:
  secretName: crapi-tls
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - crapi.lab.local
