---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crapi

resources:
  - deployment-identity.yaml
  - deployment-community.yaml
  - deployment-workshop.yaml
  - deployment-web.yaml
  - deployment-mailhog.yaml
  - deployment-mongodb.yaml
  - deployment-postgres.yaml
  - services.yaml
  - certificate.yaml
  - ingress.yaml
