---
apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: owasp-crs
  namespace: nginx-ingress
spec:
  policy:
    name: owasp-crs
    description: "OWASP CRS baseline policy for lab security testing"
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
    applicationLanguage: utf-8
    enforcementMode: blocking
    blocking-settings:
      violations:
        - name: VIOL_HTTP_PROTOCOL
          alarm: true
          block: true
        - name: VIOL_EVASION
          alarm: true
          block: true
        - name: VIOL_REQUEST_MAX_LENGTH
          alarm: true
          block: true
        - name: VIOL_MANDATORY_HEADER
          alarm: true
          block: false
        - name: VIOL_COOKIE_MODIFIED
          alarm: true
          block: false
        - name: VIOL_URL
          alarm: true
          block: true
        - name: VIOL_URL_LENGTH
          alarm: true
          block: true
        - name: VIOL_URL_METACHAR
          alarm: true
          block: true
