---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vapi-tls
  namespace: vapi
spec:
  secretName: vapi-tls
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - vapi.lab.local
